os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test -workspace skirun.xcworkspace -scheme "skirun" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.1,name=iPhone XR" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod install --repo-update

# safelist
branches:
  only:
  - master
  - dev

pods:
  rm -rf Pods
  bundle install
  bundle exec pod install
