os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test -workspace skirun.xcworkspace -scheme "skirun" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.1,name=iPhone XR" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod install --repo-update
    - sed -i ‘’ ‘/<key>$BUNDLE_ID</{n;s/id/com.google.firebase.quickstart.skirun/;}’ GoogleService-Info.plist 
    - sed -i ‘’ ‘s/$REVERSED_CLIENT/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/’ skirun/Info.plist 

# safelist
branches:
  only:
  - master
  - dev

pods:
  rm -rf Pods
  bundle install
  bundle exec pod install
